// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrth1995/go-mockva/pkg/repository (interfaces: DBTransactionManager)
//
// Generated by this command:
//
//	mockgen -destination=pkg/repository/mock/mockTransactionManager.go -package=mock github.com/mrth1995/go-mockva/pkg/repository DBTransactionManager
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockDBTransactionManager is a mock of DBTransactionManager interface.
type MockDBTransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockDBTransactionManagerMockRecorder
	isgomock struct{}
}

// MockDBTransactionManagerMockRecorder is the mock recorder for MockDBTransactionManager.
type MockDBTransactionManagerMockRecorder struct {
	mock *MockDBTransactionManager
}

// NewMockDBTransactionManager creates a new mock instance.
func NewMockDBTransactionManager(ctrl *gomock.Controller) *MockDBTransactionManager {
	mock := &MockDBTransactionManager{ctrl: ctrl}
	mock.recorder = &MockDBTransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBTransactionManager) EXPECT() *MockDBTransactionManagerMockRecorder {
	return m.recorder
}

// Transaction mocks base method.
func (m *MockDBTransactionManager) Transaction(fc func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", fc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockDBTransactionManagerMockRecorder) Transaction(fc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockDBTransactionManager)(nil).Transaction), fc)
}
