// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrth1995/go-mockva/pkg/repository (interfaces: AccountTransactionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mockAccountTransactionRepository.go -package=mock github.com/mrth1995/go-mockva/pkg/repository AccountTransactionRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	domain "github.com/mrth1995/go-mockva/pkg/domain"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAccountTransactionRepository is a mock of AccountTransactionRepository interface.
type MockAccountTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountTransactionRepositoryMockRecorder is the mock recorder for MockAccountTransactionRepository.
type MockAccountTransactionRepositoryMockRecorder struct {
	mock *MockAccountTransactionRepository
}

// NewMockAccountTransactionRepository creates a new mock instance.
func NewMockAccountTransactionRepository(ctrl *gomock.Controller) *MockAccountTransactionRepository {
	mock := &MockAccountTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockAccountTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountTransactionRepository) EXPECT() *MockAccountTransactionRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockAccountTransactionRepository) Save(trx *domain.AccountTransaction, tx *gorm.DB) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", trx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccountTransactionRepositoryMockRecorder) Save(trx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountTransactionRepository)(nil).Save), trx, tx)
}
