// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrth1995/go-mockva/pkg/repository (interfaces: AccountRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/mockAccountRepository.go -package=mock github.com/mrth1995/go-mockva/pkg/repository AccountRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/mrth1995/go-mockva/pkg/domain"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// FindAndLockAccountBalance mocks base method.
func (m *MockAccountRepository) FindAndLockAccountBalance(ctx context.Context, accountID string) (*domain.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAndLockAccountBalance", ctx, accountID)
	ret0, _ := ret[0].(*domain.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndLockAccountBalance indicates an expected call of FindAndLockAccountBalance.
func (mr *MockAccountRepositoryMockRecorder) FindAndLockAccountBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndLockAccountBalance", reflect.TypeOf((*MockAccountRepository)(nil).FindAndLockAccountBalance), ctx, accountID)
}

// FindByID mocks base method.
func (m *MockAccountRepository) FindByID(ctx context.Context, accountId string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, accountId)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountRepositoryMockRecorder) FindByID(ctx, accountId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountRepository)(nil).FindByID), ctx, accountId)
}

// Save mocks base method.
func (m *MockAccountRepository) Save(ctx context.Context, newAccount *domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, newAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAccountRepositoryMockRecorder) Save(ctx, newAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAccountRepository)(nil).Save), ctx, newAccount)
}

// Update mocks base method.
func (m *MockAccountRepository) Update(ctx context.Context, updatedAccount *domain.Account) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, updatedAccount)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAccountRepositoryMockRecorder) Update(ctx, updatedAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAccountRepository)(nil).Update), ctx, updatedAccount)
}

// UpdateBalance mocks base method.
func (m *MockAccountRepository) UpdateBalance(ctx context.Context, accountBalance *domain.AccountBalance, tx *gorm.DB) (*domain.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, accountBalance, tx)
	ret0, _ := ret[0].(*domain.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockAccountRepositoryMockRecorder) UpdateBalance(ctx, accountBalance, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccountRepository)(nil).UpdateBalance), ctx, accountBalance, tx)
}
