// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrth1995/go-mockva/pkg/service (interfaces: AccountService)
//
// Generated by this command:
//
//	mockgen -destination=mock/mockAccountService.go -package=mock github.com/mrth1995/go-mockva/pkg/service AccountService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/mrth1995/go-mockva/pkg/domain"
	model "github.com/mrth1995/go-mockva/pkg/model"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAccountService is a mock of AccountService interface.
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
	isgomock struct{}
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService.
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance.
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// Edit mocks base method.
func (m *MockAccountService) Edit(ctx context.Context, id string, edit *model.AccountEdit) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Edit", ctx, id, edit)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edit indicates an expected call of Edit.
func (mr *MockAccountServiceMockRecorder) Edit(ctx, id, edit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edit", reflect.TypeOf((*MockAccountService)(nil).Edit), ctx, id, edit)
}

// FindAndLockAccountBalance mocks base method.
func (m *MockAccountService) FindAndLockAccountBalance(ctx context.Context, accountID string) (*domain.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAndLockAccountBalance", ctx, accountID)
	ret0, _ := ret[0].(*domain.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndLockAccountBalance indicates an expected call of FindAndLockAccountBalance.
func (mr *MockAccountServiceMockRecorder) FindAndLockAccountBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndLockAccountBalance", reflect.TypeOf((*MockAccountService)(nil).FindAndLockAccountBalance), ctx, accountID)
}

// FindByID mocks base method.
func (m *MockAccountService) FindByID(ctx context.Context, id string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAccountServiceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAccountService)(nil).FindByID), ctx, id)
}

// Register mocks base method.
func (m *MockAccountService) Register(ctx context.Context, register *model.AccountRegister) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, register)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAccountServiceMockRecorder) Register(ctx, register any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAccountService)(nil).Register), ctx, register)
}

// UpdateBalance mocks base method.
func (m *MockAccountService) UpdateBalance(ctx context.Context, accountBalance *domain.AccountBalance, tx *gorm.DB) (*domain.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, accountBalance, tx)
	ret0, _ := ret[0].(*domain.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockAccountServiceMockRecorder) UpdateBalance(ctx, accountBalance, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccountService)(nil).UpdateBalance), ctx, accountBalance, tx)
}
